import Head from 'next/head'

export default function IGAQ() {
    return (
        <>
            <Head>
                <title>William Chu</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="faviconLight.svg" media="(prefers-color-scheme: dark)" />
                <link rel="icon" href="faviconDark.svg" media="(prefers-color-scheme: light)" />
            </Head>
            <div>igaq</div>
        </>
    )
}